export const GENRES = {
  // Основные жанры
  drama: "Драма",
  comedy: "Комедия",
  action: "Боевик",
  thriller: "Триллер",
  horror: "Ужасы",
  romance: "Романтика",
  adventure: "Приключения",
  scifi: "Фантастика",
  fantasy: "Фэнтези",
  mystery: "Мистика",
  crime: "Криминал",
  detective: "Детектив",
  animation: "Анимация",
  family: "Семейное",
  documentary: "Документальный",
  history: "Историческое",
  war: "Военный",
  western: "Вестерн",
  musical: "Мюзикл",
  sport: "Спортивный",
  biography: "Биография",
  film_noir: "Нуар",
  short: "Короткометражка",
  news: "Новости",
  reality_tv: "Реалити-шоу",
  talk_show: "Ток-шоу",
  game_show: "Игровое шоу",
  "stand-up": "Стендап",
  music: "Музыкальный",
  "tv-movie": "ТВ-фильм",
};
